#!/bin/bash

alias go-hyper="hyper"
alias dash="$HOME/Documents/Resources/Programs/dashlane"
alias dash-note="$HOME/Documents/Resources/Programs/dashlane note"
alias dash-pass="$HOME/Documents/Resources/Programs/dashlane password"
alias go-firefox="firefox"
alias go-deja-dup="deja-dup"
alias go-codium="flatpak run com.vscodium.codium"
alias go-inkscape="inkscape"
alias go-virtualbox="virtualbox"
alias go-calibre="calibre"
alias go-obsidian="flatpak run md.obsidian.Obsidian"
alias go-vlc="vlc"
alias gc="git commit -s -m"
alias gsa="git status -uall"
alias gp="git push origin"
alias ga="git add"
